server:
  port: 8080

springdoc:
  packagesToScan: com.employee
  pathsToMatch: /employees/**, /oauth/token

logging:
  level:
    org.springframework.security: DEBUG

####### resource server configuration properties
spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/dev
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/dev
